# Use the official Traefik image as the base
FROM traefik:latest

# (Optional) Add custom labels or environment variables here
LABEL maintainer="m4tt3o"

# Ensure the config directory exists
RUN mkdir -p /etc/traefik/